title: moyinoluwa
name: Moyinoluwa's website
description: Android Dev ğŸ‘©ğŸ¾â€ğŸ’» Conference Speaker ğŸ—£ Marathoner ğŸƒğŸ¾â€â™€ï¸
url: https://moyinoluwa.dev
google_analytics: UA-143422084-1
theme: jekyll-theme-architect
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
